import type { Job, Customer, Staff, Operation, TimePunch, QCEvent, Equipment } from '@/types';

export const mockCustomers: Customer[] = [
  {
    id: '1',
    company_name: 'Acme Manufacturing',
    contact_name: 'John Smith',
    email: 'john@acme.com',
    phone: '555-0100',
    address: '123 Industrial Way',
    city: 'Springfield',
    state: 'IL',
    zip: '62701',
    billing_email: 'billing@acme.com',
    payment_terms: 'net_30',
    notes: 'Preferred customer - 10% discount',
    created_at: new Date('2024-01-15').toISOString(),
    updated_at: new Date('2024-01-15').toISOString(),
  },
  {
    id: '2',
    company_name: 'BuildRight Construction',
    contact_name: 'Sarah Johnson',
    email: 'sarah@buildright.com',
    phone: '555-0200',
    address: '456 Builder Lane',
    city: 'Springfield',
    state: 'IL',
    zip: '62702',
    billing_email: 'ap@buildright.com',
    payment_terms: 'net_60',
    notes: null,
    created_at: new Date('2024-02-20').toISOString(),
    updated_at: new Date('2024-02-20').toISOString(),
  },
];

export const mockStaff: Staff[] = [
  {
    id: '1',
    email: 'manager@biltwood.com',
    first_name: 'Mike',
    last_name: 'Thompson',
    employee_id: 'BW001',
    role: ['admin', 'manager'],
    department: 'management',
    status: 'active',
    manager_id: null,
    photo_url: null,
    qr_code: null,
    hourly_rate: 35.00,
    created_at: new Date('2023-01-01').toISOString(),
    updated_at: new Date('2023-01-01').toISOString(),
  },
  {
    id: '2',
    email: 'operator1@biltwood.com',
    first_name: 'Carlos',
    last_name: 'Rodriguez',
    employee_id: 'BW002',
    role: ['operator'],
    department: 'production',
    status: 'active',
    manager_id: '1',
    photo_url: null,
    qr_code: null,
    hourly_rate: 22.50,
    created_at: new Date('2023-03-15').toISOString(),
    updated_at: new Date('2023-03-15').toISOString(),
  },
  {
    id: '3',
    email: 'qa@biltwood.com',
    first_name: 'Lisa',
    last_name: 'Chen',
    employee_id: 'BW003',
    role: ['qa'],
    department: 'qa',
    status: 'active',
    manager_id: '1',
    photo_url: null,
    qr_code: null,
    hourly_rate: 25.00,
    created_at: new Date('2023-05-10').toISOString(),
    updated_at: new Date('2023-05-10').toISOString(),
  },
];

export const mockJobs: Job[] = [
  {
    id: '1',
    job_number: 'BW2412-0001',
    customer_id: '1',
    status: 'in_progress',
    quote_id: null,
    description: 'Steel railings - Gloss black powder coat',
    priority: 'standard',
    due_date: new Date('2025-01-15').toISOString().split('T')[0],
    drive_folder_id: null,
    qr_code: null,
    total_quoted: 1250.00,
    total_actual: null,
    created_by: '1',
    created_at: new Date('2024-12-01').toISOString(),
    updated_at: new Date('2024-12-01').toISOString(),
    completed_at: null,
  },
  {
    id: '2',
    job_number: 'BW2412-0002',
    customer_id: '2',
    status: 'qa',
    quote_id: null,
    description: 'Aluminum window frames - White semi-gloss',
    priority: 'rush',
    due_date: new Date('2024-12-20').toISOString().split('T')[0],
    drive_folder_id: null,
    qr_code: null,
    total_quoted: 3400.00,
    total_actual: 3250.00,
    created_by: '1',
    created_at: new Date('2024-12-05').toISOString(),
    updated_at: new Date('2024-12-05').toISOString(),
    completed_at: null,
  },
  {
    id: '3',
    job_number: 'BW2411-0087',
    customer_id: '1',
    status: 'complete',
    quote_id: null,
    description: 'Handrails - Matte black texture',
    priority: 'standard',
    due_date: new Date('2024-11-30').toISOString().split('T')[0],
    drive_folder_id: null,
    qr_code: null,
    total_quoted: 890.00,
    total_actual: 875.00,
    created_by: '1',
    created_at: new Date('2024-11-15').toISOString(),
    updated_at: new Date('2024-11-28').toISOString(),
    completed_at: new Date('2024-11-28').toISOString(),
  },
];

export const mockTimePunches: TimePunch[] = [
  {
    id: '1',
    staff_id: '2',
    punch_type: 'clock_in',
    punch_method: 'qr_scan',
    timestamp: new Date('2024-12-07T08:00:00').toISOString(),
    location: 'Station 1',
    notes: null,
    status: 'approved',
    reviewed_by: '1',
    reviewed_at: new Date('2024-12-07T17:30:00').toISOString(),
  },
  {
    id: '2',
    staff_id: '2',
    punch_type: 'clock_out',
    punch_method: 'qr_scan',
    timestamp: new Date('2024-12-07T17:00:00').toISOString(),
    location: 'Station 1',
    notes: null,
    status: 'approved',
    reviewed_by: '1',
    reviewed_at: new Date('2024-12-07T17:30:00').toISOString(),
  },
  {
    id: '3',
    staff_id: '3',
    punch_type: 'clock_in',
    punch_method: 'google_auth',
    timestamp: new Date('2024-12-07T07:30:00').toISOString(),
    location: 'Mobile',
    notes: null,
    status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
  },
];

export const mockQCEvents: QCEvent[] = [
  {
    id: '1',
    job_id: '2',
    part_id: null,
    operation_id: null,
    inspector_id: '3',
    result: 'pass',
    defect_types: [],
    severity: null,
    photo_urls: [],
    corrective_action: null,
    notes: 'All parts meet quality standards',
    inspected_at: new Date('2024-12-06T14:30:00').toISOString(),
  },
  {
    id: '2',
    job_id: '1',
    part_id: null,
    operation_id: null,
    inspector_id: '3',
    result: 'fail',
    defect_types: ['orange_peel', 'contamination'],
    severity: 'major',
    photo_urls: [],
    corrective_action: 'Strip and recoat affected parts',
    notes: 'Found contamination on 3 pieces, orange peel on finish',
    inspected_at: new Date('2024-12-05T11:00:00').toISOString(),
  },
];

export const mockEquipment: Equipment[] = [
  {
    id: '1',
    equipment_name: 'Powder Booth #1',
    equipment_type: 'booth',
    manufacturer: 'Nordson',
    model: 'CB-4000',
    serial_number: 'NRD-2019-0045',
    meter_type: 'hours',
    current_meter: 2847,
    service_interval: 500,
    next_service_due: 3000,
    drive_folder_id: null,
    qr_code: null,
    status: 'operational',
    notes: null,
    created_at: new Date('2023-01-01').toISOString(),
  },
  {
    id: '2',
    equipment_name: 'Cure Oven',
    equipment_type: 'oven',
    manufacturer: 'Grieve',
    model: 'GR-800',
    serial_number: 'GRV-2020-0123',
    meter_type: 'cycles',
    current_meter: 5432,
    service_interval: 1000,
    next_service_due: 6000,
    drive_folder_id: null,
    qr_code: null,
    status: 'operational',
    notes: 'Temperature calibration due next month',
    created_at: new Date('2023-01-01').toISOString(),
  },
];

// Helper to use mock data when Supabase is not configured
// Always use mock data for demo mode
export const useMockData = true;
